apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
      - name: stock-api
        image: widgetario/stock-api:21.03
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_CONNECTION_STRING
          valueFrom: 
            secretKeyRef:
              name: stock-api-secret
              key: db.string
        
