apiVersion: v1
kind: Secret
metadata:
  name: stock-api-secret
data:
  db.string: aG9zdD1wcm9kdWN0cy1kYiBwb3J0PTU0MzIgdXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1tKmxlc3RvbmUzIGRibmFtZT1wb3N0Z3JlcyBzc2xtb2RlPWRpc2FibGU=