apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: product-db
        image: widgetario/products-db:21.03
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: product-db-secret
              key: db.password
        
