{{- define "helm-library.config-map" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-config-map
  namespace: {{ default "dcj-service-test" .Values.namespace }}
  annotations:
    checksum/config: {{ toYaml .Values.environment | sha256sum }}
data:
  file1.json: |
{{ .Values.content | toPrettyJson | indent 4 }}
  file2.json: |
{{ .Values.content | toPrettyJson | indent 4 }}
{{- end -}}