{{- define "helm-library.secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-secrets
  namespace: {{ default "dcj-service-test" .Values.namespace }}
  annotations:
    checksum/config: {{ toYaml .Values.secrets | sha256sum }}
type: Opaque
data: 
  {{- range $key, $val := .Values.secrets.db_secrets }}
  {{ $key }}: {{ $val |  quote }}
  {{- end}}