apiVersion: v1
kind: ConfigMap
metadata:
  name: web-logging
data:
  logging.json: |-
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": "Warning",
          "Override": {
            "WiredBrain": "Information"
          }
        }
      }
    }
    