replicaCount: 1
app_name: "products-db"
namespace: "widgetario"
svc_port: 5432
svc_targetport: 5432
container:
  image_name: "widgetario/products-db:21.03"
  port: "5432"
  livenessProbe:
    tcpSocket:
      port: 5432
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 5432
    initialDelaySeconds: 20
    periodSeconds: 10
secrets:
  db_secrets:
    enc_key: 'njsprlwa8d64fvnsfnjsk61156aodlmr'
    enc_iv: '48914829jfs2'
    sql_user: "root"
    sql_password: "password"
    redis_password: "rpass"
    redis_prefix: "k34234:"